### ISSUE TITLE
Error: du invalid option -I

### ISSUE THREAD

**Issue by ctjhoa** [rajasegar/eax#2]
Hi,

on `Arch Linux`, `du` doesn't have `-I` option

```
du: invalid option -- 'I'
Try 'du --help' for more information.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:316:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:316:20)
    at Pipe.<anonymous> (net.js:672:12)
(node:2625471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by ctjhoa** [comment]
`man du`:
BSD: https://www.freebsd.org/cgi/man.cgi?du
Linux:  https://linux.die.net/man/1/du

**Comment by rajasegar** [comment]
Ahh my bad, I knew this might happen, if we are using the standard shell command execution with an Unix flavor like Darwin (Mac OS). Let me check and see how we can go about this..
Meanwhile appreciate a PR if possible...
